sleepy_lio_node:
  ros__parameters:
    use_sim_time: false
    event_reorder_window: 0.07 #最好大于帧率最低的传感器相邻帧时间
    align_gravity_with_z_axiz: true
    initialization_window: 1.0
    initialization_min_samples: 200
    gravity_norm: 9.80665
    state_frame: livox_frame
    min_distance: 0.5
    max_distance: 20.0
    point_filter_num: 5
    sensor:
      pointcloud_sensors: ["pc1"]
      pc1:
        topic: /livox/lidar
        type: livox_custom_msg
        frame_id: livox_frame
        sensor_in_frame_t: [-0.011, -0.02329, 0.04412]
        sensor_in_frame_R: [1.0, 0.0, 0.0,
                            0.0, 1.0, 0.0,
                            0.0, 0.0, 1.0]
      imu_sensors: ["imu1"]
      imu1:
        topic: /livox/imu
        frame_id: livox_frame
        acc_scale: 1.0
        sensor_in_frame_t: [0.0, 0.0, 0.0]
        sensor_in_frame_R: [1.0, 0.0, 0.0,
                            0.0, 1.0, 0.0,
                            0.0, 0.0, 1.0]

    
